# fly.toml app configuration file generated for backend-green-log-7069 on 2024-09-12T15:52:24-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-green-log-7069'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
