# fly.toml app configuration file generated for backend-moodmap on 2024-09-12T18:51:02-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-moodmap'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
